---
- hosts: webserver
  become: yes
  tasks: 
       - include_tasks: myfilehandle.yml

       - name : i want to install httpd on RedHat node
         yum:
            name: httpd
            state: present
         when: ansible_os_family == "RedHat"

       - name : i want to replace httpd template with my page
         template: 
              src: mytemplate/mypage2.j2
              dest: /var/www/html/index.html