---
- hosts: all
  become: yes
  tasks:
          - name: install openJDK 8 on node
            apt:
                  name: openjdk-8-jre
                  state: present
            when: ansible_os_family == "Debian"