---
- hosts: webserver
  become: yes
  tasks:
          - name: install openJDK 8 on node
            apt:
                  name: openjdk-8-jre
                  state: present
            when: ansible_os_family == "Debian"



          - name: install openJDK 8 on node
            yum: 
                  name: java-1.8.0-openjdk 
                  state: present
            when: ansible_os_family == "RedHat"     
            