---
- hosts: webserver
  become: yes
  tasks:
          - name: install openJDK 8 on node
            apt:
                  name: "{{myubuntuopenjdk}}"
                  state: present
            when: ansible_os_family == "Debian"



          - name: install openJDK 8 on node
            yum: 
                  name: "{{myredhatopenjdk}}"
                  state: present
            when: ansible_os_family == "RedHat"     
