---
- hosts: 172.31.2.237
  become: yes
  tasks:
      - name : i want to run linux command on ubuntu node
        command: hostname -f
        register: myresult

      - name : i want to display result of linux command
        debug:
           msg: "{{myresult}}"

      - name : i waant to list git
        apt:
           name: git
           state: present
        when: myresult.stderr ==""

      - name : i want to list tree
        apt:
           name: tree
           state: present
        when: myresult.stderr !=""
        
      
